version: '3.8'

name: global-customer-go-api

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123  # The password for the 'sa' user.
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data  # Mount the './data' directory to '/var/opt/mssql/data' in the container.
