// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: eganow/api/customer_payload.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonalOrBusinessGroupValue int32

const (
	PersonalOrBusinessGroupValue_UNKNOWN  PersonalOrBusinessGroupValue = 0
	PersonalOrBusinessGroupValue_PERSONAL PersonalOrBusinessGroupValue = 1
	PersonalOrBusinessGroupValue_BUSINESS PersonalOrBusinessGroupValue = 2
)

// Enum value maps for PersonalOrBusinessGroupValue.
var (
	PersonalOrBusinessGroupValue_name = map[int32]string{
		0: "UNKNOWN",
		1: "PERSONAL",
		2: "BUSINESS",
	}
	PersonalOrBusinessGroupValue_value = map[string]int32{
		"UNKNOWN":  0,
		"PERSONAL": 1,
		"BUSINESS": 2,
	}
)

func (x PersonalOrBusinessGroupValue) Enum() *PersonalOrBusinessGroupValue {
	p := new(PersonalOrBusinessGroupValue)
	*p = x
	return p
}

func (x PersonalOrBusinessGroupValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PersonalOrBusinessGroupValue) Descriptor() protoreflect.EnumDescriptor {
	return file_eganow_api_customer_payload_proto_enumTypes[0].Descriptor()
}

func (PersonalOrBusinessGroupValue) Type() protoreflect.EnumType {
	return &file_eganow_api_customer_payload_proto_enumTypes[0]
}

func (x PersonalOrBusinessGroupValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PersonalOrBusinessGroupValue.Descriptor instead.
func (PersonalOrBusinessGroupValue) EnumDescriptor() ([]byte, []int) {
	return file_eganow_api_customer_payload_proto_rawDescGZIP(), []int{0}
}

// used when generating OTP
type GenerateOTPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MobileNumber string                       `protobuf:"bytes,1,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	EmailAddress string                       `protobuf:"bytes,2,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	GroupValue   PersonalOrBusinessGroupValue `protobuf:"varint,3,opt,name=group_value,json=groupValue,proto3,enum=eganow.api.PersonalOrBusinessGroupValue" json:"group_value,omitempty"`
	CountryCode  string                       `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	LanguageId   string                       `protobuf:"bytes,5,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
}

func (x *GenerateOTPRequest) Reset() {
	*x = GenerateOTPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eganow_api_customer_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateOTPRequest) ProtoMessage() {}

func (x *GenerateOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eganow_api_customer_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateOTPRequest.ProtoReflect.Descriptor instead.
func (*GenerateOTPRequest) Descriptor() ([]byte, []int) {
	return file_eganow_api_customer_payload_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateOTPRequest) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

func (x *GenerateOTPRequest) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *GenerateOTPRequest) GetGroupValue() PersonalOrBusinessGroupValue {
	if x != nil {
		return x.GroupValue
	}
	return PersonalOrBusinessGroupValue_UNKNOWN
}

func (x *GenerateOTPRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *GenerateOTPRequest) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

var File_eganow_api_customer_payload_proto protoreflect.FileDescriptor

var file_eganow_api_customer_payload_proto_rawDesc = []byte{
	0x0a, 0x21, 0x65, 0x67, 0x61, 0x6e, 0x6f, 0x77, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65, 0x67, 0x61, 0x6e, 0x6f, 0x77, 0x2e, 0x61, 0x70, 0x69, 0x22,
	0xed, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4f, 0x54, 0x50, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x49, 0x0a, 0x0b, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x65, 0x67, 0x61, 0x6e, 0x6f, 0x77, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x4f, 0x72, 0x42, 0x75, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x49, 0x64, 0x2a,
	0x47, 0x0a, 0x1c, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x4f, 0x72, 0x42, 0x75, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x50, 0x45, 0x52, 0x53, 0x4f, 0x4e, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x55,
	0x53, 0x49, 0x4e, 0x45, 0x53, 0x53, 0x10, 0x02, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x67, 0x61, 0x6e, 0x6f, 0x77, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_eganow_api_customer_payload_proto_rawDescOnce sync.Once
	file_eganow_api_customer_payload_proto_rawDescData = file_eganow_api_customer_payload_proto_rawDesc
)

func file_eganow_api_customer_payload_proto_rawDescGZIP() []byte {
	file_eganow_api_customer_payload_proto_rawDescOnce.Do(func() {
		file_eganow_api_customer_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_eganow_api_customer_payload_proto_rawDescData)
	})
	return file_eganow_api_customer_payload_proto_rawDescData
}

var file_eganow_api_customer_payload_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_eganow_api_customer_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_eganow_api_customer_payload_proto_goTypes = []interface{}{
	(PersonalOrBusinessGroupValue)(0), // 0: eganow.api.PersonalOrBusinessGroupValue
	(*GenerateOTPRequest)(nil),        // 1: eganow.api.GenerateOTPRequest
}
var file_eganow_api_customer_payload_proto_depIdxs = []int32{
	0, // 0: eganow.api.GenerateOTPRequest.group_value:type_name -> eganow.api.PersonalOrBusinessGroupValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_eganow_api_customer_payload_proto_init() }
func file_eganow_api_customer_payload_proto_init() {
	if File_eganow_api_customer_payload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_eganow_api_customer_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateOTPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eganow_api_customer_payload_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eganow_api_customer_payload_proto_goTypes,
		DependencyIndexes: file_eganow_api_customer_payload_proto_depIdxs,
		EnumInfos:         file_eganow_api_customer_payload_proto_enumTypes,
		MessageInfos:      file_eganow_api_customer_payload_proto_msgTypes,
	}.Build()
	File_eganow_api_customer_payload_proto = out.File
	file_eganow_api_customer_payload_proto_rawDesc = nil
	file_eganow_api_customer_payload_proto_goTypes = nil
	file_eganow_api_customer_payload_proto_depIdxs = nil
}
