// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: eganow/api/customer_service.proto

/*
Package pb is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package pb

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_CustomerAccountOnboarding_GenerateOTPForNewCustomerCreation_0(ctx context.Context, marshaler runtime.Marshaler, client CustomerAccountOnboardingClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GenerateOTPRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.GenerateOTPForNewCustomerCreation(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_CustomerAccountOnboarding_GenerateOTPForNewCustomerCreation_0(ctx context.Context, marshaler runtime.Marshaler, server CustomerAccountOnboardingServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GenerateOTPRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.GenerateOTPForNewCustomerCreation(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterCustomerAccountOnboardingHandlerServer registers the http handlers for service CustomerAccountOnboarding to "mux".
// UnaryRPC     :call CustomerAccountOnboardingServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterCustomerAccountOnboardingHandlerFromEndpoint instead.
func RegisterCustomerAccountOnboardingHandlerServer(ctx context.Context, mux *runtime.ServeMux, server CustomerAccountOnboardingServer) error {

	mux.Handle("POST", pattern_CustomerAccountOnboarding_GenerateOTPForNewCustomerCreation_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/eganow.api.CustomerAccountOnboarding/GenerateOTPForNewCustomerCreation", runtime.WithHTTPPathPattern("/v1/customer/onboarding/generate-otp"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_CustomerAccountOnboarding_GenerateOTPForNewCustomerCreation_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_CustomerAccountOnboarding_GenerateOTPForNewCustomerCreation_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterCustomerAccountOnboardingHandlerFromEndpoint is same as RegisterCustomerAccountOnboardingHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterCustomerAccountOnboardingHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterCustomerAccountOnboardingHandler(ctx, mux, conn)
}

// RegisterCustomerAccountOnboardingHandler registers the http handlers for service CustomerAccountOnboarding to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterCustomerAccountOnboardingHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterCustomerAccountOnboardingHandlerClient(ctx, mux, NewCustomerAccountOnboardingClient(conn))
}

// RegisterCustomerAccountOnboardingHandlerClient registers the http handlers for service CustomerAccountOnboarding
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "CustomerAccountOnboardingClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "CustomerAccountOnboardingClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "CustomerAccountOnboardingClient" to call the correct interceptors.
func RegisterCustomerAccountOnboardingHandlerClient(ctx context.Context, mux *runtime.ServeMux, client CustomerAccountOnboardingClient) error {

	mux.Handle("POST", pattern_CustomerAccountOnboarding_GenerateOTPForNewCustomerCreation_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/eganow.api.CustomerAccountOnboarding/GenerateOTPForNewCustomerCreation", runtime.WithHTTPPathPattern("/v1/customer/onboarding/generate-otp"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_CustomerAccountOnboarding_GenerateOTPForNewCustomerCreation_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_CustomerAccountOnboarding_GenerateOTPForNewCustomerCreation_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_CustomerAccountOnboarding_GenerateOTPForNewCustomerCreation_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3}, []string{"v1", "customer", "onboarding", "generate-otp"}, ""))
)

var (
	forward_CustomerAccountOnboarding_GenerateOTPForNewCustomerCreation_0 = runtime.ForwardResponseMessage
)
