apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: eganowdevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-deployment
  template:
    metadata:
      labels:
        app: mssql-deployment
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: 'Y'
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SA_PASSWORD
                  name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: mssql-storage
          name: mssqldb
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: mssql-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  namespace: eganowdevops
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: template-gateway-deployment
  template:
    metadata:
      labels:
        app: template-gateway-deployment
    spec:
      containers:
        - env:
            - name: GRPC_SERVER_PORT
              value: '34567'
            - name: GRPC_SERVER_HOST
              value: localhost
            - name: HTTP_SERVER_PORT
              value: '9876'
            - name: HTTP_SERVER_HOST
              value: localhost
            - name: HMAC_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: HMAC_SECRET_KEY
                  name: server
            - name: DB_CONN_URL
              valueFrom:
                secretKeyRef:
                  key: DB_CONN_URL
                  name: mssql
            - name: DB_HOST
              value: localhost
            - name: DB_PORT
              value: '1433'
            - name: DB_USER
              value: pop
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SA_PASSWORD
                  name: mssql
            - name: DB_NAME
              value: master
            - name: DB_DRIVER
              value: sqlserver
            - name: DB_SSL_MODE
              value: disable
            - name: DB_MAX_IDLE_CONNS
              value: '10'
            - name: DB_MAX_OPEN_CONNS
              value: '100'
            - name: DB_CONN_MAX_LIFETIME
              value: '30'
            - name: DB_CONN_MAX_IDLE_TIME
              value: '5'
          image: eganowdevteam/eganow-template-go-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9876 # http
            - containerPort: 34567 # grpc
          name: server
