apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: eganowdevops
  labels:
    app: mssql-service
spec:
  selector:
    app: mssql-deployment
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: template-server-service
  namespace: eganowdevops
  labels:
    app: template-gateway-server
spec:
  selector:
    app: template-gateway-deployment
  ports:
    - protocol: TCP
      name: http
      port: 9876
      targetPort: 9876
    - protocol: TCP
      name: grpc
      port: 34567
      targetPort: 34567
  type: ClusterIP
